modeling/data_ingestion.py
this and a79fa0cbdad5b094b5552e6458f1dd1dff87c3ec..544e9d53b6804c1b65a3703830ba504504680fe5 fixes #9 .
=> refactored resnet extractor

modeling/train.py, requirements.txt
=> code to train models

modeling/backbones.py, modeling/data_ingestion.py, modeling/train.py, requirements.txt
fixes #3. 
Specifically, 
1. re-implemented original frame number calculation
2. added `mod` field indicating "transitional" frames
3. added many backbone models to experiment
=> data ingestion with many backbones

modeling/train.py
=> k-fold validation implementation

.gitignore, modeling/train.py
* updated ignore
* setting model for `eval` mode when evaluating (set off dropouts)
* removed meaningless model "resetting" at each training cycle
* made results directory generation more portable (fixing #21)
=> fixing error

.dockerignore, README.md, metadata.py
While reviewing the submitted `v1.0` app, I found the readme file contains too specific and somewhat duplicate information.
=> cleaning up readme

classify.py
This is another commit to fix some bone-headed commit mistakes
=> Adding more config changes

Containerfile, modeling/classify.py
=> fixed cv2 error when failed to open video file

modeling/classify.py, modeling/stitch.py, modeling/train.py
This fixes an old problem where you could not run a model that uses post-binning. This is fixed in the sense that you can now have a model created while a post-binning strategy was defined in the training config file. That same strategy will now be used while running the classifier (note though that it is the stitcher and not the classifier itself that uses post-binning).
=> Fixing post binning for the classifier

app.py, modeling/classify.py
=> added logging of computation times

app.py, metadata.py, modeling/config/classifier.yml
=> option to turn OFF stitcher

app.py, modeling/classify.py
* fixes #85  
* include monkeypatching SDK helper for still image extraction (partial fix for #69)
=> Optimizing video seek time for still image extraction

app.py, modeling/stitch.py, modeling/train.py
=> TimePoint outputs now include softmax for `NEG` label

Containerfile, app.py, requirements.txt
=> fixes possible disparity in sampling rate and actual sampling

modeling/data_loader.py
=> fixed sinusoidal encoding bug 

modeling/train.py
=> fixed mismatched method calls and signatures

modeling/classify.py, modeling/data_loader.py, modeling/train.py, test/test_pos_enc.py
=> fixed model configs not thoroughly passed to the feature extractor

app.py, metadata.py
=> fixed unable to disable `tfLabelMapPreset` by `nopreset` value

app.py
=> changed line order for faster failing when input file unavailable

modeling/classify.py, modeling/gridsearch.py, modeling/validate.py
=> eval mode for backbone models and classifier model

modeling/backbones.py, modeling/data_loader.py, requirements.txt
=> adding more backbone models
